version: "3.8"
services:
  pkapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "7086:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - pg_net
networks:
  pg_net:
